@startuml 04-clases-registrar-llegada

title Diagrama de Clases - Registrar Llegada del Paciente

class Secretaria {
    -idSecretaria: int
    -nombre: String

    +registrarLlegada(paciente: Paciente, turno: Turno): LlegadaPaciente
    +actualizarEstadoTurno(turno: Turno, estado: EstadoTurno): void
}

enum EstadoTurno {
    PROGRAMADO
    EN_PROGRESO
    COMPLETADO
    CANCELADO
}

class Paciente 
    -idPaciente: int
    -nombre: String
    -dni: String

    +consultarTurno(): Turno
}

class Turno {
    -idTurno: int
    -fecha: LocalDate
    -hora: String
    -estado: String

    +validarTurnoDelDia(): boolean
    +cambiarEstado(estado: String): void
}

class LlegadaPaciente {
    -idLlegada: int
    -horaLlegada: LocalTime
    
    +registrar(): void
}

class Agenda {
    -idAgenda: int

    - turnos: List<Turno>

    +buscarTurno(paciente: Paciente): Turno
}


Secretaria --> Paciente
Secretaria --> LlegadaPaciente
Secretaria --> Turno
Paciente --> Turno
Agenda --> Turno
LlegadaPaciente *-- Turno

@enduml