@startuml 05-secuencia-registrar-llegada-05

title Diagrama de Secuencia - Registrar Llegada

actor Paciente as paciente
actor Secretaria as secretaria
actor Medico as medico

participant "Agenda:agenda" as agenda
participant "Turno:turno" as turno

paciente -> secretaria: confirmarAsistencia(paciente, turno)
secretaria -> agenda: accederAgendaDiaria(fecha)

activate agenda

agenda --> secretaria: mostrar turnos del dia
secretaria -> turno: buscarTurno(paciente)

activate turno

turno --> secretaria: turno confirmado
secretaria -> turno: registrarLlegada(horaReal)
turno -> turno: cambiarEstado("Presente")
turno -/ agenda: registrarEnHistorial(horaReal)
agenda --> medico: notificar presencia

deactivate turno
destroy turno

deactivate agenda
destroy agenda

@enduml
