@startuml 05-secuencia-autorizar-sobreturno-04

title Diagrama de Secuencia - Autorizar Sobreturno

actor Secretaria as secretaria
actor Medico as medico
actor Paciente as paciente

participant "Agenda:agenda" as agenda
participant "Turno:turno" as turno

secretaria -> agenda: intentarCrearTurno(fecha, hora, paciente)

activate agenda

agenda --> secretaria: advertencia sobreturno no disponible
secretaria -> medico: solicitarAutorizacion()
medico --> secretaria: autorizar sobreturno
secretaria -> agenda: confirmarAutorizacion(paciente, fecha, hora)

create turno

agenda -> turno: crearTurno(paciente, medico, sobreturno=true)

activate turno

turno -> turno: cambiarEstado("Confirmado")
turno -/ agenda: registrarEnHistorial(usuario=secretaria, autorizadoPor=medico)
agenda --> paciente: enviar notificacion

deactivate turno
destroy turno

deactivate agenda
destroy agenda

@enduml