@startuml 05-secuencia-cancelar-turno-02

title Diagrama de Secuencia - Cancelar Turno
' Nombre del escenario: Cancelar Turno - Flujo Principal
' Archivo: diagramas/03-escenarios-casos-de-uso/03-cancelar-turno-flujo-principal.md
' Objetivo: Representar la cancelación de un turno a solicitud del paciente, involucrando secretaria, paciente y sistema, basado en responsabilidades de CRC (Secretaria gestiona turnos, Turno modifica estados, Agenda libera horarios).

actor Paciente as paciente
actor Secretaria as secretaria
participant "Agenda:agenda" as agenda
participant "Turno:turno" as turno

paciente -> secretaria: solicitarCancelacion()

secretaria -> agenda: buscarTurno()
activate agenda

agenda -> turno: obtenerTurno()
activate turno

agenda --> secretaria: mostrarTurno


secretaria -> turno: cancelarTurno()


turno -> turno: cambiarEstado
turno --> agenda: liberarHorario
turno -/ agenda: registrarEnHistorial()

agenda --> paciente: enviarNotificacion

deactivate turno
deactivate agenda

destroy turno
destroy agenda

@enduml